#!/usr/bin/env bash
# 7-highlander script that ignores SIGTERM and displays a message

trap 'echo "I am invincible!!!"' SIGTERM
trap 'exit 0' SIGINT SIGQUIT

while true; do
    echo "To infinity and beyond"
    sleep 1
done
